name: deploy

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.102.3'
        extended: true

    - name: Build
      run: hugo --minify -b "https://mlg.eng.cam.ac.uk/hugo-site/"

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

# If known hosts change too often, can do insecurely like this
    # - name: Adding Known Hosts
      # run: ssh-keyscan -H {{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy
      run: rsync -avz --omit-dir-times --no-perms --delete -e 'ssh -A -J ag2198@$gate.eng.cam.ac.uk' public/ ag2198@cbl-fs.eng.cam.ac.uk:/var/www/mlg/hugo-site/
