name: deploy

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.102.3'
        extended: true

    - name: Build
      run: hugo --minify

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

# If known hosts change too often, can do insecurely like this
    # - name: Adding Known Hosts
      # run: ssh-keyscan -H {{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy
      run: rsync -avz --delete -e 'ssh -A -J ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}' public/ ${{ secrets.SSH_USER }}@cbl-fs.eng.cam.ac.uk:~/public_html/mlg-test
      #run: rsync -avz --delete -e "ssh -A ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} ssh" public/ ${{ secrets.SSH_USER }}@cbl-fs.eng.cam.ac.uk:~/public_html/mlg-test
      #run: rsync -avz --delete public/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/public_html/mlg-test
